# Generated by Django 2.2.4 on 2019-08-20 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boxlock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 20, 0, 40, 32, 902361, tzinfo=utc), verbose_name='permission added'),
            preserve_default=False,
        ),
    ]
